In [7]:
import numpy as kb

In [8]:
kb

<module 'numpy' from 'C:\\Users\\jbhar\\Downloads\\Anaconda\\Lib\\site-packages\\numpy\\__init__.py'>

In [9]:
kb.__version__

'1.26.4'

In [11]:
p = [1,2,3,4,5]
print(p)
type(p)

[1, 2, 3, 4, 5]


list

In [14]:
p = kb.array(l)

In [15]:
p

array([1, 2, 3, 4, 5, 6])

In [16]:
type(p)

numpy.ndarray

In [18]:
p1 = (2,3,4,5,6,7,8)
print(p1)
print(type(p1))

(2, 3, 4, 5, 6, 7, 8)
<class 'tuple'>


In [19]:
l2 = kb.array(p1)

In [20]:
l2

array([2, 3, 4, 5, 6, 7, 8])

In [21]:
kb.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [23]:
kb.arange(10,50,7) #(start , stop , step)

array([10, 17, 24, 31, 38, 45])

In [25]:
kb.arange(30,20,10) # array will be empty because the 2nd argument is less than third argument)

array([], dtype=int32)

In [27]:
kb.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
n = kb.arange(-14, 3)
n

array([-14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,
        -1,   0,   1,   2])

In [29]:
kb.zeros(1)

array([0.])

In [30]:
kb.zeros(8, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
k = kb.zeros(8, dtype = int)
print(k)
print(type(k))

[0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [32]:
m = kb.zeros(1)
print(m)
type(m)

[0.]


numpy.ndarray

In [36]:
j = kb.zeros((3,1))
j

array([[0.],
       [0.],
       [0.]])

In [37]:
kb.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
kb.ones(3)

array([1., 1., 1.])

In [39]:
kb.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [46]:
k = kb.ones((10,9) , dtype = int)

In [47]:
k

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
k = kb.ones((4,6))

In [50]:
k

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
k = kb.ones((4,6), dtype = int)

In [52]:
k

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [1]:
import numpy as np

In [2]:
rand(3,6)

NameError: name 'rand' is not defined

In [3]:
np.random.rand(3,6)

array([[0.32704743, 0.10907532, 0.95632674, 0.16701225, 0.11930774,
        0.85737617],
       [0.49376833, 0.62039681, 0.86609916, 0.49060655, 0.15880159,
        0.39524534],
       [0.17468399, 0.73432731, 0.76086835, 0.27394936, 0.3709047 ,
        0.1508392 ]])

In [4]:
np.random.randint(3,6)

5

In [7]:
np.random.randint(10,20,5)

array([13, 17, 14, 11, 10])

In [8]:
np.random.randint(1,6,3) # here 3rd argument is range i.e is volume

array([5, 3, 1])

In [9]:
np.random.rand(2)

array([0.85501026, 0.09663115])

In [10]:
np.random.randint(1)

0

In [11]:
np.random.randint(30,20,10) #1st arg should be less than 2nd arg

ValueError: low >= high

In [12]:
np.random.randint(-30,20,10)

array([ -9,  -3,   0, -12,  -7, -16,  -7,   7,   4,  12])

In [13]:
np.random.randint(10,21,3)

array([15, 18, 12])

In [14]:
np.random.randint(1,12,10)

array([ 7, 11,  7,  9, 11, 11,  5,  1,  2,  6])

In [15]:
np.random.randint(1,10,10)

array([4, 3, 1, 3, 8, 5, 4, 5, 4, 1])

In [17]:
np.random.randint(10,30,(8,8))

array([[12, 18, 25, 26, 14, 14, 28, 18],
       [26, 26, 18, 12, 26, 16, 22, 29],
       [19, 27, 11, 27, 18, 10, 19, 21],
       [11, 15, 23, 26, 23, 17, 17, 29],
       [24, 16, 14, 10, 26, 27, 19, 18],
       [17, 22, 12, 20, 29, 11, 15, 15],
       [14, 27, 13, 12, 24, 13, 23, 17],
       [22, 20, 28, 25, 24, 23, 27, 20]])

In [19]:
np.random.randint(10,200,(10,10))

array([[ 19, 144, 185, 126,  55, 164,  42, 184, 121,  60],
       [135,  11, 156,  92, 185, 158, 131, 171,  71, 110],
       [ 31, 129, 111, 194,  41, 115, 196, 198, 123,  71],
       [181, 144,  76,  71,  82,  27,  94,  54, 102, 137],
       [ 38,  13,  80,  86,  62,  76,  79, 132, 101, 175],
       [107, 197, 155, 162,  68, 152, 153,  87, 151, 173],
       [138, 141, 154,  80,  46, 188,  15, 152,  18,  63],
       [164,  78, 102, 131, 112, 111,  47,  35,  84, 103],
       [ 73,  38,  20,  98, 142,  52, 176,  43, 107, 108],
       [192, 171, 176, 114, 136,  20,  94, 184,  62,  82]])

In [20]:
np.arange(2,3)

array([2])

In [21]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
p = np.arange(0,16).reshape(4,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
p.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [37]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [38]:
type(b)

numpy.ndarray

# Slicing

In [39]:
b

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [40]:
b[:]

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [41]:
b[1:]

array([[12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [43]:
b[1:3]

array([[12, 19, 16, 19],
       [18, 19, 13, 19]])

In [44]:
b[3:4]

array([[15, 16, 14, 13]])

In [45]:
b[-1:]

array([[17, 11, 18, 11]])

In [46]:
b

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [47]:
b[1,2]

16

In [48]:
b[0,1]

17

In [49]:
b[1,-1]

19

In [50]:
b[2:3]

array([[18, 19, 13, 19]])

In [51]:
b[0:-2]

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19]])

In [52]:
b[-5,-3]

17

In [53]:
b

array([[18, 17, 15, 17],
       [12, 19, 16, 19],
       [18, 19, 13, 19],
       [15, 16, 14, 13],
       [17, 11, 18, 11]])

In [54]:
b[-4:2]

array([[12, 19, 16, 19]])

In [55]:
b[-4,2]

16

In [56]:
b[-5:2]

array([[18, 17, 15, 17],
       [12, 19, 16, 19]])

# Operations

In [57]:
a = np.random.randint(10,20,10)
a

array([15, 10, 18, 17, 13, 17, 19, 11, 12, 12])

In [58]:
id(a)

3125426291504

In [60]:
arr = [0,1,2,3,4,5]

In [61]:
np.array(arr)

array([0, 1, 2, 3, 4, 5])

In [62]:
arr2 = np.random.randint(0,200,(9,9))

In [63]:
arr2

array([[ 48, 149,   1, 158,  78,  15, 138, 179,   5],
       [113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [157, 145,   5, 105,  13,  25,  75,  45, 188],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [138,  80,  36, 111, 161, 173, 153,  40,  12],
       [  3,  97,  49,  69,  91,  90, 136,  34, 162]])

In [64]:
arr[:]

[0, 1, 2, 3, 4, 5]

In [65]:
arr[:4]

[0, 1, 2, 3]

In [66]:
arr2

array([[ 48, 149,   1, 158,  78,  15, 138, 179,   5],
       [113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [157, 145,   5, 105,  13,  25,  75,  45, 188],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [138,  80,  36, 111, 161, 173, 153,  40,  12],
       [  3,  97,  49,  69,  91,  90, 136,  34, 162]])

In [67]:
arr2[1:]

array([[113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [157, 145,   5, 105,  13,  25,  75,  45, 188],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [138,  80,  36, 111, 161, 173, 153,  40,  12],
       [  3,  97,  49,  69,  91,  90, 136,  34, 162]])

In [68]:
arr2[0:5]

array([[ 48, 149,   1, 158,  78,  15, 138, 179,   5],
       [113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102]])

In [69]:
arr2[1,4]

41

In [70]:
arr2[-5:5]

array([[ 48, 179, 131,  72,  83, 191,  26, 110, 102]])

In [71]:
arr2[-5,5]

191

In [72]:
arr2[-5,-5]

83

In [73]:
arr2[::-1]

array([[  3,  97,  49,  69,  91,  90, 136,  34, 162],
       [138,  80,  36, 111, 161, 173, 153,  40,  12],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [157, 145,   5, 105,  13,  25,  75,  45, 188],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 48, 149,   1, 158,  78,  15, 138, 179,   5]])

In [74]:
arr2[::-2]

array([[  3,  97,  49,  69,  91,  90, 136,  34, 162],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 48, 149,   1, 158,  78,  15, 138, 179,   5]])

In [75]:
arr2[::-4]

array([[  3,  97,  49,  69,  91,  90, 136,  34, 162],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [ 48, 149,   1, 158,  78,  15, 138, 179,   5]])

In [76]:
arr2[::1]

array([[ 48, 149,   1, 158,  78,  15, 138, 179,   5],
       [113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [157, 145,   5, 105,  13,  25,  75,  45, 188],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [138,  80,  36, 111, 161, 173, 153,  40,  12],
       [  3,  97,  49,  69,  91,  90, 136,  34, 162]])

In [77]:
arr2[::2]

array([[ 48, 149,   1, 158,  78,  15, 138, 179,   5],
       [ 10, 127, 142,  68, 137, 186,  43,  41, 129],
       [ 48, 179, 131,  72,  83, 191,  26, 110, 102],
       [ 45, 123, 137,  43,  27, 152, 163, 150, 159],
       [  3,  97,  49,  69,  91,  90, 136,  34, 162]])

In [78]:
arr2[1:4:2]

array([[113, 157, 107,  42,  41,  59,  39, 160,  93],
       [ 29, 125, 104, 139,   4, 133,  48,  12,  48]])

In [79]:
arr

[0, 1, 2, 3, 4, 5]

In [85]:
arr = np.array(arr)
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr.max()

5

In [87]:
arr.min()

0

In [88]:
arr2.max()

191

In [89]:
arr2.min()

1

In [90]:
arr.mean()

2.5

In [91]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [92]:
from numpy import *
a = array(arr)
median(a)

2.5

In [94]:
from numpy import *
b = array([1,2,3,4,9])
median(b)                   

3.0

In [95]:
from numpy import *
c = array([1,2,3,4,6,8])
mode(c)                         #numpy does not have funtion mode

NameError: name 'mode' is not defined

In [96]:
arr

array([0, 1, 2, 3, 4, 5])

In [97]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [102]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
arr.reshape(2,3 , order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [104]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
arr.reshape(2,3 , order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
arr.reshape(2,3 , order = 'F') #fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [109]:
arr.reshape(2,3 , order = 'A')

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [111]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [112]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [113]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

# Indexing

In [114]:
mat =np.arange(0,100).reshape(10,10)

In [115]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
row = 4
col = 5

In [117]:
col

5

In [118]:
row

4

In [119]:
mat[row,col]

45

In [120]:
mat[4,5]

45

In [121]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [123]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [124]:
col = 6

In [125]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [126]:
mat[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [127]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [129]:
row

4

In [130]:
col

6

In [131]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [132]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [133]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
mat[col:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [136]:
mat[1,4]

14

In [137]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [139]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [141]:
mat[3:-4]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [142]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [143]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [146]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [147]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [148]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [149]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [150]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [152]:
mat[0,1]

1

In [153]:
mat[1,6]

16

In [154]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [155]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [156]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [158]:
mat[3,5]

35

In [159]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[1:2,3:4]

array([[13]])

In [162]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# Masking

In [163]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
id(mat)

3125441124880

In [165]:
type(mat)

numpy.ndarray

In [167]:
mat = [mat<50]

[array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False]])]

In [168]:
mat = np.arange(0,100).reshape(10,10)

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [171]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [174]:
mat[mat == 50]

array([50])

In [175]:
k = mat[mat>=50]
k

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [176]:
m = mat[mat<=50]

In [177]:
m 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])